favicon: null
name: BraleyWoodCreations
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#797067'
    - '#A89C90'
    - '#4F301C'
    - '#DEC59D'
    - '#20140B'
  lightness: 0.625
typography_spectrum: 0.509667
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.971536
analytics:
  twitter: null
  google: null
  facebook: null
