name: BraleyWoodCreations
favicon: null
layout_spectrum: 0.971536
typography_spectrum: 0.60033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#797067'
    - '#A89C90'
    - '#4F301C'
    - '#DEC59D'
    - '#20140B'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
